accounts/urls.py
from django.urls import re_path
from .import views

app_name = 'profile'

urlpatterns = [
	re_path(r'^$', views.profile_list, name='profile-list'),
	re_path(r'^detail/(?P<username>[\w-]+)/$', views.profile_detail, name='profile-detail'),
]

agro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('allauth.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('dashboard/services', include('services.urls')),
    path('dashboard/accounts', include('accounts.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dashboard/urls.py
from django.urls import re_path
from .import views

app_name = 'dashboard'

urlpatterns = [
	re_path(r'^$', views.dashboard, name='dashboard'),
	re_path(r'^offer-advice/$', views.create_advice, name='offer-advice'),
	re_path(r'^advice/$', views.advice_list, name='advice-list'),
	re_path(r'^services/$', views.service_list, name='service-list'),
]

services/urls.py
from django.urls import re_path
from .import views

app_name = 'services'

urlpatterns = [
	re_path(r'^$', views.create_service, name='create-service'),
]

dashboard/models.py
from django.db import models
from django.utils.text import slugify

class Advice(models.Model):
	slug = models.SlugField(unique=True, blank=True, null=True)
	specialization = models.CharField(unique=True, max_length=50)
	content = models.TextField()
	created = models.DateTimeField(auto_now_add=True)
	modified = models.DateTimeField(auto_now=True)

	def  __str__(self):
		return self.specialization

	def save(self, *args, **kwargs):
		self.slug = slugify(self.specialization)
		super().save(*args, **kwargs)

dashboard/forms.py
from django import forms
from .models import Advice

class AdviceForm(forms.ModelForm):
	class Meta:
		model = Advice
		fields = ['specialization', 'content']

	specialization = forms.CharField(
		required = True,
		label = 'Specialization',
		widget = forms.TextInput(
			attrs = {
				'class': 'form-control',
				'placeholder': 'Area of specialization'
			}),
	)

	content = forms.CharField(
		required = True,
		label = 'Message',
		widget = forms.Textarea(
			attrs = {
				'class': 'form-control mb-3',
				'placeholder': 'What can you tell us...',
				'rows': 5,
		}),
	)

dashboard/views.py
from django.shortcuts import render
from .forms import AdviceForm
from .models import Advice
from services.models import Service

def dashboard(request):
	template_name = 'dashboard/dashboard.html'

	context = {

	}
	return render(request, template_name, context)

def create_advice(request):
	template_name = 'dashboard/create_advice.html'

	if request.method == 'POST':
		form = AdviceForm(request.POST or None, label_suffix='')
		if form.is_valid():
			form.save()
	else:
		form = AdviceForm(label_suffix='')
	
	context = {
		'form': form,
	}
	return render(request, template_name, context)

def advice_list(request):
	template_name = 'dashboard/advice_list.html'
	advice_list = Advice.objects.all()

	context = {
		'advice_list': advice_list,
	}
	return render(request, template_name, context)

def service_list(request):
	template_name = 'dashboard/service_list.html'
	services = Service.objects.all()

	context = {
		'services': services,
	}
	return render(request, template_name, context)

dashboard/templates/dashboard/includes/dashboard_scripts.html
{% load static %}

<script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

<script type="text/javascript" src="{% static 'home/js/app-style-switcher.js' %}"></script>

<script type="text/javascript" src="{% static 'home/js/waves.js' %}"></script>

<script type="text/javascript" src="{% static 'home/js/sidebarmenu.js' %}"></script>

<script type="text/javascript" src="{% static 'home/js/custom.js' %}"></script>

dashboard/templates/dashboard/includes/sidebar.html
{% load static %}

<nav class="sidebar-nav">
	<ul id="sidebarnav">
		<li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link"
			href="{% url 'dashboard:dashboard' %}" aria-expanded="false"><i class="fa fa-columns"
			aria-hidden="true"></i><span class="hide-menu">Dashboard</span></a>
		</li>
		<li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link"
			href="{% url 'profile:profile-detail' request.user.username %}" aria-expanded="false">
			<i class="fa fa-user" aria-hidden="true"></i><span class="hide-menu">Profile</span></a>
		</li>

		<li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link"
			href="{% url 'profile:profile-list' %}" aria-expanded="false"><i class="fa fa-font"
			aria-hidden="true"></i><span class="hide-menu">Farmers</span></a>
		</li>

		<li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link"
			href="{% url 'services:create-service' %}" aria-expanded="false"><i class="fa fa-info-circle"
			aria-hidden="true"></i><span class="hide-menu">Create Farmer Service</span></a>
		</li>

		<li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link"
			href="{% url 'dashboard:service-list' %}" aria-expanded="false"><i class="fa fa-info-circle"
			aria-hidden="true"></i><span class="hide-menu">Available Services</span></a>
		</li>

		<li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link"
			href="{% url 'dashboard:offer-advice' %}" aria-expanded="false"><i class="fa fa-info-circle"
			aria-hidden="true"></i><span class="hide-menu">Offer Advice</span></a>
		</li>

		<li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link"
			href="{% url 'dashboard:advice-list' %}" aria-expanded="false"><i class="fa fa-info-circle"
			aria-hidden="true"></i><span class="hide-menu">Get Advice</span></a>
		</li>

	</ul>
</nav>

dashboard/templates/dashboard/includes/topnav.html
{% load static %}

<header class="topbar" data-navbarbg="skin5">
<nav class="navbar top-navbar navbar-expand-md navbar-dark">
	<div class="navbar-header" data-logobg="skin6">

		<a class="navbar-brand" href="#">

			<span class="logo-text">
				<span class="sf-logo-text">Smart Admin</span>
			</span>
		</a>

		<a class="nav-toggler waves-effect waves-light text-dark d-block d-md-none"
		href="javascript:void(0)"><i class="ti-menu ti-close"></i></a>
	</div>

	<div class="navbar-collapse collapse" id="navbarSupportedContent" data-navbarbg="skin5">
		<ul class="navbar-nav d-none d-md-block d-lg-none">
			<li class="nav-item">
				<a class="nav-toggler nav-link waves-effect waves-light text-white"
				href="javascript:void(0)"><i class="ti-menu ti-close"></i></a>
			</li>
		</ul>

		<ul class="navbar-nav ml-auto d-flex align-items-center">

			<li class=" in">
				<form role="search" class="app-search d-none d-md-block mr-3">
					<input type="text" placeholder="Search..." class="form-control mt-0">
					<a href="" class="active">
						<i class="fa fa-search"></i>
					</a>
				</form>
			</li>

			<li>
				<a class="profile-pic" href="#">
					<img src="{% static 'plugins/images/users/varun.jpg' %}" alt="user-img" width="36"
					class="img-circle"><span class="text-white font-medium">{{ user }}</span>
				</a>
			</li>

			<li>
				<a class="profile-pic" href="{% url 'account_logout' %}">
					Logout
				</a>
			</li>

			</ul>
		</div>
	</nav>
</header>